package com.omerfaruk.dongu

import android.Manifest
import android.app.*
import android.content.*
import android.content.pm.PackageManager
import android.os.*
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.app.NotificationCompat
import androidx.core.app.NotificationManagerCompat
import androidx.core.content.ContextCompat
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewmodel.compose.viewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import org.json.JSONArray
import org.json.JSONObject
import java.time.*
import java.time.format.DateTimeFormatter
import java.time.format.TextStyle
import java.time.temporal.ChronoUnit
import java.util.Locale
import kotlin.math.roundToInt
import kotlin.math.sqrt

private val Pink=Color(0xFFF2A7C2); private val PinkStrong=Color(0xFFFF7FAF)
private val Lavender=Color(0xFFD9A7FF); private val Bg=Color(0xFF101014)
private val CardBg=Color(0xFF19191F); private val Soft=Color(0xFF24242C)
private val Text2=Color(0xFFBEB5BA)
private val colors=darkColorScheme(primary=Pink,onPrimary=Color(0xFF321421),secondary=Lavender,background=Bg,surface=CardBg,surfaceVariant=Soft,onBackground=Color(0xFFF8F2F5),onSurface=Color(0xFFF8F2F5),onSurfaceVariant=Text2)

data class DayEntry(val d:Long,val start:Boolean=false,val end:Boolean=false,val mood:String="",val note:String="",val pain:Int=0,val spotting:Boolean=false){val date:LocalDate get()=LocalDate.ofEpochDay(d); fun empty()=!start&&!end&&mood.isBlank()&&note.isBlank()&&pain==0&&!spotting}
data class Stats(val avgCycle:Int?,val avgPeriod:Int?,val lengths:List<Int>,val next:LocalDate?,val ovulation:LocalDate?,val fertileStart:LocalDate?,val fertileEnd:LocalDate?,val regularity:String,val deviation:Double?)
data class UiState(val entries:List<DayEntry> = emptyList(),val stats:Stats=calc(emptyList()),val reminder:Boolean=true,val reminderDays:Int=2)
data class Interval(val start:LocalDate,val end:LocalDate)

private class Store(ctx:Context){
    private val p=ctx.getSharedPreferences("dongu_data",Context.MODE_PRIVATE)
    fun load():List<DayEntry>{val raw=p.getString("entries","[]")?:"[]";return runCatching{val a=JSONArray(raw);buildList{for(i in 0 until a.length()){val o=a.getJSONObject(i);add(DayEntry(o.getLong("d"),o.optBoolean("s"),o.optBoolean("e"),o.optString("m"),o.optString("n"),o.optInt("p").coerceIn(0,5),o.optBoolean("sp")))}}.sortedBy{it.d}}.getOrDefault(emptyList())}
    fun save(xs:List<DayEntry>){val a=JSONArray();xs.sortedBy{it.d}.forEach{x->a.put(JSONObject().put("d",x.d).put("s",x.start).put("e",x.end).put("m",x.mood).put("n",x.note).put("p",x.pain).put("sp",x.spotting))};p.edit().putString("entries",a.toString()).apply()}
    fun reminder()=p.getBoolean("reminder",true); fun days()=p.getInt("reminder_days",2).coerceIn(0,7)
    fun saveReminder(on:Boolean,days:Int){p.edit().putBoolean("reminder",on).putInt("reminder_days",days.coerceIn(0,7)).apply()}
}

class CycleVm(app:Application):AndroidViewModel(app){
    private val store=Store(app); private val _s=MutableStateFlow(UiState(entries=store.load(),reminder=store.reminder(),reminderDays=store.days()));val s:StateFlow<UiState> = _s.asStateFlow()
    init{refresh(_s.value.entries)}
    private fun refresh(xs:List<DayEntry>){val st=calc(xs);_s.value=_s.value.copy(entries=xs.sortedBy{it.d},stats=st);if(_s.value.reminder)Reminder.schedule(getApplication(),st.next,_s.value.reminderDays)else Reminder.cancel(getApplication())}
    private fun mutate(date:LocalDate,f:(DayEntry)->DayEntry){val xs=_s.value.entries.toMutableList();val i=xs.indexOfFirst{it.d==date.toEpochDay()};val old=if(i>=0)xs[i]else DayEntry(date.toEpochDay());val n=f(old);if(n.empty()){if(i>=0)xs.removeAt(i)}else if(i>=0)xs[i]=n else xs.add(n);store.save(xs);refresh(xs)}
    fun toggleStart(d:LocalDate)=mutate(d){it.copy(start=!it.start)};fun toggleEnd(d:LocalDate)=mutate(d){it.copy(end=!it.end)}
    fun saveDay(d:LocalDate,m:String,n:String,p:Int,sp:Boolean)=mutate(d){it.copy(mood=m,note=n.trim(),pain=p.coerceIn(0,5),spotting=sp)}
    fun reminder(on:Boolean){_s.value=_s.value.copy(reminder=on);store.saveReminder(on,_s.value.reminderDays);refresh(_s.value.entries)}
    fun reminderDays(v:Int){_s.value=_s.value.copy(reminderDays=v.coerceIn(0,7));store.saveReminder(_s.value.reminder,_s.value.reminderDays);refresh(_s.value.entries)}
}

class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);channel(this);setContent{MaterialTheme(colorScheme=colors){val ask=rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()){};App(onAsk={if(Build.VERSION.SDK_INT>=33&&ContextCompat.checkSelfPermission(this,Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)ask.launch(Manifest.permission.POST_NOTIFICATIONS)})}}}}

private fun channel(c:Context){if(Build.VERSION.SDK_INT>=26){c.getSystemService(NotificationManager::class.java).createNotificationChannel(NotificationChannel("dongu_reminders","Döngü hatırlatmaları",NotificationManager.IMPORTANCE_DEFAULT))}}
object Reminder{private const val RC=4401;fun schedule(c:Context,next:LocalDate?,days:Int){cancel(c);if(next==null)return;val z=next.minusDays(days.toLong()).atTime(9,0).atZone(ZoneId.systemDefault());if(!z.isAfter(ZonedDateTime.now()))return;val i=Intent(c,PeriodReminderReceiver::class.java).putExtra("days",days);val pi=PendingIntent.getBroadcast(c,RC,i,PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE);(c.getSystemService(Context.ALARM_SERVICE) as AlarmManager).setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,z.toInstant().toEpochMilli(),pi)};fun cancel(c:Context){val pi=PendingIntent.getBroadcast(c,RC,Intent(c,PeriodReminderReceiver::class.java),PendingIntent.FLAG_NO_CREATE or PendingIntent.FLAG_IMMUTABLE)?:return;(c.getSystemService(Context.ALARM_SERVICE) as AlarmManager).cancel(pi);pi.cancel()}}
class PeriodReminderReceiver:BroadcastReceiver(){override fun onReceive(c:Context,i:Intent){channel(c);val d=i.getIntExtra("days",0);val txt=when(d){0->"Tahmine göre regl bugün başlayabilir.";1->"Tahmine göre regl yarın başlayabilir.";else->"Tahmine göre regle yaklaşık $d gün kaldı."};val open=PendingIntent.getActivity(c,4402,Intent(c,MainActivity::class.java),PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE);val n=NotificationCompat.Builder(c,"dongu_reminders").setSmallIcon(R.drawable.ic_stat_drop).setContentTitle("Döngü").setContentText(txt).setContentIntent(open).setAutoCancel(true).build();if(Build.VERSION.SDK_INT<33||ContextCompat.checkSelfPermission(c,Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED)NotificationManagerCompat.from(c).notify(4403,n)}}
class BootReceiver:BroadcastReceiver(){override fun onReceive(c:Context,i:Intent){if(i.action!=Intent.ACTION_BOOT_COMPLETED)return;val st=Store(c);if(st.reminder())Reminder.schedule(c,calc(st.load()).next,st.days())}}

enum class Tab{CAL,STATS,SETTINGS}
@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun App(vm:CycleVm= viewModel(),onAsk:()->Unit){val s by vm.s.collectAsState();var tab by remember{mutableStateOf(Tab.CAL)};var day by remember{mutableStateOf<LocalDate?>(null)};Scaffold(containerColor=Bg,bottomBar={NavigationBar(containerColor=CardBg){NavigationBarItem(tab==Tab.CAL,{tab=Tab.CAL},{Icon(Icons.Default.CalendarMonth,null)},{Text("Takvim")});NavigationBarItem(tab==Tab.STATS,{tab=Tab.STATS},{Icon(Icons.Default.BarChart,null)},{Text("Analiz")});NavigationBarItem(tab==Tab.SETTINGS,{tab=Tab.SETTINGS},{Icon(Icons.Default.Settings,null)},{Text("Ayarlar")})}}){pad->when(tab){Tab.CAL->CalendarScreen(s,Modifier.padding(pad),{day=it},{vm.toggleStart(LocalDate.now())});Tab.STATS->StatsScreen(s,Modifier.padding(pad));Tab.SETTINGS->SettingsScreen(s,Modifier.padding(pad),{vm.reminder(it);if(it)onAsk()},{vm.reminderDays(it)})}};day?.let{d->DaySheet(d,s.entries.firstOrNull{it.d==d.toEpochDay()},{day=null},{vm.toggleStart(d)},{vm.toggleEnd(d)}){m,n,p,sp->vm.saveDay(d,m,n,p,sp);day=null}}}

@Composable private fun CalendarScreen(s:UiState,mod:Modifier,onDate:(LocalDate)->Unit,onQuick:()->Unit){var month by remember{mutableStateOf(YearMonth.now())};val today=LocalDate.now();val todayStart=s.entries.any{it.d==today.toEpochDay()&&it.start};LazyColumn(mod.fillMaxSize().statusBarsPadding(),contentPadding=PaddingValues(18.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{Text("Döngü",fontSize=30.sp,fontWeight=FontWeight.Bold);Text(headline(s.stats),color=Text2,fontSize=13.sp)};item{Surface(color=if(todayStart)Soft else Pink,contentColor=if(todayStart)Color.White else Color(0xFF321421),shape=RoundedCornerShape(24.dp),modifier=Modifier.fillMaxWidth().clickable{onQuick()}){Row(Modifier.padding(18.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.WaterDrop,null);Spacer(Modifier.width(12.dp));Column{Text(if(todayStart)"Bugünkü başlangıç kaydedildi" else "Bugün regl başladı",fontWeight=FontWeight.Bold);Text(if(todayStart)"Geri almak için dokun" else "Tek dokunuşla başlangıcı işaretle",fontSize=12.sp)}}}};item{Card(colors=CardDefaults.cardColors(containerColor=CardBg),shape=RoundedCornerShape(28.dp)){Column(Modifier.padding(12.dp)){MonthHeader(month,{month=month.minusMonths(1)},{month=month.plusMonths(1)});WeekHeader();MonthGrid(month,today,s,onDate);Legend()}}};item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Metric("Ort. döngü",s.stats.avgCycle?.let{"$it gün"}?:"—",Modifier.weight(1f));Metric("Ort. regl",s.stats.avgPeriod?.let{"$it gün"}?:"—",Modifier.weight(1f));Metric("Düzen",s.stats.regularity,Modifier.weight(1f))}}}}
@Composable private fun MonthHeader(m:YearMonth,prev:()->Unit,next:()->Unit){val tr=Locale("tr","TR");val name=m.month.getDisplayName(TextStyle.FULL,tr).replaceFirstChar{it.titlecase(tr)};Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){IconButton(prev){Icon(Icons.Default.ChevronLeft,null)};Text("$name ${m.year}",Modifier.weight(1f),textAlign=TextAlign.Center,fontSize=18.sp,fontWeight=FontWeight.SemiBold);IconButton(next){Icon(Icons.Default.ChevronRight,null)}}}
@Composable private fun WeekHeader(){Row(Modifier.fillMaxWidth()){listOf("Pzt","Sal","Çar","Per","Cum","Cmt","Paz").forEach{Text(it,Modifier.weight(1f).padding(vertical=6.dp),textAlign=TextAlign.Center,fontSize=10.sp,color=Text2)}}}
@Composable private fun MonthGrid(m:YearMonth,today:LocalDate,s:UiState,onDate:(LocalDate)->Unit){val off=m.atDay(1).dayOfWeek.value-1;val map=s.entries.associateBy{it.d};val ints=intervals(s.entries);Column{repeat(6){r->Row(Modifier.fillMaxWidth()){repeat(7){c->val n=r*7+c-off+1;if(n !in 1..m.lengthOfMonth())Spacer(Modifier.weight(1f).height(62.dp))else{val d=m.atDay(n);val e=map[d.toEpochDay()];val actual=ints.any{!d.isBefore(it.start)&&!d.isAfter(it.end)};val pred=isPred(d,s.stats);val fertile=s.stats.fertileStart!=null&&s.stats.fertileEnd!=null&&!d.isBefore(s.stats.fertileStart)&&!d.isAfter(s.stats.fertileEnd);Cell(d,e,d==today,actual,pred,fertile,d==s.stats.ovulation,Modifier.weight(1f)){onDate(d)}}}}}}}
@Composable private fun Cell(d:LocalDate,e:DayEntry?,today:Boolean,actual:Boolean,pred:Boolean,fertile:Boolean,ovu:Boolean,mod:Modifier,onClick:()->Unit){val bg=when{actual->PinkStrong.copy(.85f);pred->Pink.copy(.18f);fertile->Lavender.copy(.10f);else->Color.Transparent};val border=when{today->Color.White.copy(.7f);pred->Pink.copy(.6f);fertile->Lavender.copy(.4f);else->Color.Transparent};Box(mod.height(62.dp).padding(2.dp).clip(RoundedCornerShape(15.dp)).background(bg).border(1.dp,border,RoundedCornerShape(15.dp)).clickable{onClick()}){if(!e?.note.isNullOrBlank())Box(Modifier.align(Alignment.TopEnd).padding(7.dp).size(5.dp).background(Pink,CircleShape));Column(Modifier.align(Alignment.Center),horizontalAlignment=Alignment.CenterHorizontally){Text(d.dayOfMonth.toString(),fontSize=13.sp,fontWeight=if(today||e?.start==true)FontWeight.Bold else FontWeight.Medium,color=if(actual)Color(0xFF321421)else Color.White);Spacer(Modifier.height(3.dp));when{!e?.mood.isNullOrBlank()->Text(e!!.mood,fontSize=15.sp);ovu->Box(Modifier.size(6.dp).background(Lavender,CircleShape));else->Spacer(Modifier.height(16.dp))}}}}
@Composable private fun Legend(){Row(Modifier.fillMaxWidth().padding(top=8.dp),horizontalArrangement=Arrangement.SpaceAround){Dot(PinkStrong,"Regl");Dot(Pink.copy(.35f),"Tahmin");Dot(Lavender.copy(.45f),"Doğurgan");Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(5.dp).background(Pink,CircleShape));Spacer(Modifier.width(4.dp));Text("Not",fontSize=10.sp,color=Text2)}}}
@Composable private fun Dot(c:Color,t:String){Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(9.dp).background(c,CircleShape));Spacer(Modifier.width(4.dp));Text(t,fontSize=10.sp,color=Text2)}}
@Composable private fun Metric(t:String,v:String,mod:Modifier=Modifier){Card(mod,colors=CardDefaults.cardColors(containerColor=CardBg),shape=RoundedCornerShape(20.dp)){Column(Modifier.padding(13.dp)){Text(t,color=Text2,fontSize=10.sp);Text(v,fontWeight=FontWeight.SemiBold,fontSize=13.sp,maxLines=1)}}}

@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun DaySheet(d:LocalDate,e:DayEntry?,dismiss:()->Unit,toggleStart:()->Unit,toggleEnd:()->Unit,save:(String,String,Int,Boolean)->Unit){var mood by remember(d,e?.mood){mutableStateOf(e?.mood.orEmpty())};var note by remember(d,e?.note){mutableStateOf(e?.note.orEmpty())};var pain by remember(d,e?.pain){mutableIntStateOf(e?.pain?:0)};var spotting by remember(d,e?.spotting){mutableStateOf(e?.spotting?:false)};var symptoms by remember{mutableStateOf((e?.pain?:0)>0||e?.spotting==true)};ModalBottomSheet(dismiss,containerColor=CardBg){Column(Modifier.fillMaxWidth().fillMaxHeight(.9f).verticalScroll(rememberScrollState()).padding(20.dp)){Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(longDate(d),fontWeight=FontWeight.Bold,fontSize=21.sp);Text("Gün detayları",color=Text2,fontSize=12.sp)};IconButton(dismiss){Icon(Icons.Default.Close,null)}};Spacer(Modifier.height(16.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button(toggleStart,Modifier.weight(1f),colors=ButtonDefaults.buttonColors(containerColor=Pink)){Text(if(e?.start==true)"Başlangıç ✓" else "Regl başladı")};OutlinedButton(toggleEnd,Modifier.weight(1f)){Text(if(e?.end==true)"Bitiş ✓" else "Regl bitti")}};Spacer(Modifier.height(22.dp));Text("Duygu durumu",fontWeight=FontWeight.SemiBold);Spacer(Modifier.height(8.dp));Mood(mood){mood=if(mood==it)"" else it};Spacer(Modifier.height(18.dp));Text("Not",fontWeight=FontWeight.SemiBold);Spacer(Modifier.height(7.dp));OutlinedTextField(note,{note=it},Modifier.fillMaxWidth(),minLines=3,maxLines=6,placeholder={Text("Bugün nasıl geçti?")},shape=RoundedCornerShape(18.dp));Spacer(Modifier.height(14.dp));Surface(color=Soft,shape=RoundedCornerShape(18.dp),modifier=Modifier.fillMaxWidth().clickable{symptoms=!symptoms}){Row(Modifier.padding(16.dp)){Text("Semptomlar",Modifier.weight(1f),fontWeight=FontWeight.SemiBold);Text(if(symptoms)"Gizle" else "Göster",color=Pink,fontSize=12.sp)}};AnimatedVisibility(symptoms){Column(Modifier.padding(top=12.dp)){Row{Text("Ağrı düzeyi",Modifier.weight(1f));Text("$pain / 5",color=Pink,fontWeight=FontWeight.Bold)};Slider(pain.toFloat(),{pain=it.roundToInt()},valueRange=0f..5f,steps=4);FilterChip(spotting,{spotting=!spotting},{Text("Lekelenme")})}};Spacer(Modifier.height(22.dp));Button({save(mood,note,pain,spotting)},Modifier.fillMaxWidth().height(52.dp),shape=RoundedCornerShape(18.dp)){Text("Kaydet",fontWeight=FontWeight.Bold)};Spacer(Modifier.height(20.dp))}}}
@Composable private fun Mood(sel:String,on:(String)->Unit){val ms=listOf("🙂","😌","🥰","😐","😔","😣","😡","😴");Column(verticalArrangement=Arrangement.spacedBy(7.dp)){ms.chunked(4).forEach{row->Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(7.dp)){row.forEach{x->val active=x==sel;Surface(color=if(active)Pink.copy(.22f)else Soft,shape=RoundedCornerShape(17.dp),modifier=Modifier.weight(1f).height(50.dp).clickable{on(x)}.then(if(active)Modifier.border(1.dp,Pink,RoundedCornerShape(17.dp))else Modifier)){Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Text(x,fontSize=23.sp)}}}}}}}

@Composable private fun StatsScreen(s:UiState,mod:Modifier){val st=s.stats;val hist=history(s.entries);LazyColumn(mod.fillMaxSize().statusBarsPadding(),contentPadding=PaddingValues(18.dp),verticalArrangement=Arrangement.spacedBy(13.dp)){item{Text("Analiz",fontSize=30.sp,fontWeight=FontWeight.Bold);Text("Kayıtların arttıkça tahminler kişiselleşir.",color=Text2,fontSize=12.sp)};item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Metric("Ortalama döngü",st.avgCycle?.let{"$it gün"}?:"Veri yok",Modifier.weight(1f));Metric("Ortalama regl",st.avgPeriod?.let{"$it gün"}?:"Veri yok",Modifier.weight(1f))}};st.next?.let{n->item{Card(colors=CardDefaults.cardColors(containerColor=Pink.copy(.12f)),shape=RoundedCornerShape(24.dp)){Column(Modifier.padding(18.dp)){Text("Tahmin",color=Pink,fontWeight=FontWeight.Bold);Text("Sonraki regl: ${shortDate(n)}",fontWeight=FontWeight.Bold,fontSize=19.sp);st.ovulation?.let{Text("Ovülasyon: ${shortDate(it)}",color=Text2,fontSize=13.sp,modifier=Modifier.padding(top=7.dp))};if(st.fertileStart!=null&&st.fertileEnd!=null)Text("Doğurganlık: ${shortDate(st.fertileStart)} – ${shortDate(st.fertileEnd)}",color=Text2,fontSize=13.sp)}}}};item{Card(colors=CardDefaults.cardColors(containerColor=CardBg),shape=RoundedCornerShape(24.dp)){Column(Modifier.padding(18.dp)){Text("Döngü düzeni",fontWeight=FontWeight.Bold);Text(st.regularity,color=Pink,fontWeight=FontWeight.SemiBold,modifier=Modifier.padding(top=5.dp));st.deviation?.let{Text("Standart sapma: ${"%.1f".format(Locale.US,it)} gün",color=Text2,fontSize=12.sp)}}}};if(st.lengths.isNotEmpty())item{Card(colors=CardDefaults.cardColors(containerColor=CardBg),shape=RoundedCornerShape(24.dp)){Column(Modifier.padding(18.dp)){Text("Geçmiş döngüler",fontWeight=FontWeight.Bold);Text("Başlangıçlar arasındaki gün sayısı",color=Text2,fontSize=12.sp);Spacer(Modifier.height(14.dp));Chart(st.lengths.takeLast(8))}}};if(hist.isNotEmpty()){item{Text("Regl geçmişi",fontWeight=FontWeight.Bold,fontSize=18.sp)};items(hist){(a,b)->HistoryRow(a,b)}}else item{Card(colors=CardDefaults.cardColors(containerColor=CardBg),shape=RoundedCornerShape(24.dp)){Text("En az iki başlangıç kaydıyla analiz oluşmaya başlar.",Modifier.padding(20.dp),color=Text2)}}}}}
@Composable private fun Chart(v:List<Int>){val lo=v.minOrNull()?:0;val hi=v.maxOrNull()?:1;val range=(hi-lo).coerceAtLeast(1);Canvas(Modifier.fillMaxWidth().height(145.dp).background(Soft,RoundedCornerShape(18.dp)).padding(14.dp)){val step=if(v.size==1)0f else size.width/(v.size-1);val pts=v.mapIndexed{i,x->Offset(if(v.size==1)size.width/2 else i*step,size.height-(((x-lo).toFloat()/range)*size.height*.72f+size.height*.14f))};for(i in 0 until pts.lastIndex)drawLine(Pink,pts[i],pts[i+1],5f,cap=StrokeCap.Round);pts.forEach{drawCircle(Pink,7f,it);drawCircle(Soft,3f,it)}};Row(Modifier.fillMaxWidth().padding(top=6.dp),horizontalArrangement=Arrangement.SpaceBetween){v.forEach{Text("$it",fontSize=10.sp,color=Text2)}}}
@Composable private fun HistoryRow(a:LocalDate,b:LocalDate?){Card(colors=CardDefaults.cardColors(containerColor=CardBg),shape=RoundedCornerShape(20.dp)){Row(Modifier.fillMaxWidth().padding(15.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.WaterDrop,null,tint=Pink);Spacer(Modifier.width(10.dp));Column(Modifier.weight(1f)){Text(shortDate(a),fontWeight=FontWeight.SemiBold);Text(if(b!=null)"Bitiş: ${shortDate(b)}" else "Bitiş kaydı yok",color=Text2,fontSize=12.sp)};if(b!=null)Text("${ChronoUnit.DAYS.between(a,b)+1} gün",color=Pink,fontWeight=FontWeight.Bold)}}}

@Composable private fun SettingsScreen(s:UiState,mod:Modifier,onRem:(Boolean)->Unit,onDays:(Int)->Unit){Column(mod.fillMaxSize().statusBarsPadding().verticalScroll(rememberScrollState()).padding(18.dp)){Text("Ayarlar",fontSize=30.sp,fontWeight=FontWeight.Bold);Text("Sade, yerel ve özel.",color=Text2,fontSize=12.sp);Spacer(Modifier.height(18.dp));Card(colors=CardDefaults.cardColors(containerColor=CardBg),shape=RoundedCornerShape(24.dp)){Column(Modifier.padding(18.dp)){Row(verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.Notifications,null,tint=Pink);Spacer(Modifier.width(10.dp));Column(Modifier.weight(1f)){Text("Regl hatırlatıcısı",fontWeight=FontWeight.Bold);Text("Tahmini tarihten önce bildirim",color=Text2,fontSize=12.sp)};Switch(s.reminder,onRem)};AnimatedVisibility(s.reminder){Column(Modifier.padding(top=14.dp)){Row{Text("Kaç gün önce?",Modifier.weight(1f));Text(if(s.reminderDays==0)"Aynı gün" else "${s.reminderDays} gün",color=Pink,fontWeight=FontWeight.Bold)};Slider(s.reminderDays.toFloat(),{onDays(it.roundToInt())},valueRange=0f..7f,steps=6)}}}};Spacer(Modifier.height(13.dp));Info("Gizlilik","Tüm kayıtlar yalnızca bu cihazda tutulur. Uygulama hesap, internet veya bulut bağlantısı istemez.");Spacer(Modifier.height(13.dp));Info("Tahminler hakkında","Regl, ovülasyon ve doğurganlık tarihleri geçmiş kayıtların ortalamasına dayalı yaklaşık tahminlerdir. Tıbbi değerlendirme veya doğum kontrol yöntemi olarak kullanılmamalıdır.");Spacer(Modifier.height(18.dp));Text("Döngü 1.0.0",color=Text2,fontSize=11.sp,modifier=Modifier.align(Alignment.CenterHorizontally))}}
@Composable private fun Info(t:String,b:String){Card(colors=CardDefaults.cardColors(containerColor=CardBg),shape=RoundedCornerShape(24.dp)){Column(Modifier.padding(18.dp)){Text(t,fontWeight=FontWeight.Bold);Text(b,color=Text2,fontSize=13.sp,lineHeight=19.sp,modifier=Modifier.padding(top=7.dp))}}}

private fun calc(xs:List<DayEntry>):Stats{val starts=xs.filter{it.start}.map{it.date}.distinct().sorted();val lens=starts.zipWithNext{a,b->ChronoUnit.DAYS.between(a,b).toInt()}.filter{it>0};val durations=durations(xs);val ac=lens.takeIf{it.isNotEmpty()}?.average()?.roundToInt();val ap=durations.takeIf{it.isNotEmpty()}?.average()?.roundToInt();val dev=if(lens.size>=2){val av=lens.average();sqrt(lens.sumOf{(it-av)*(it-av)}/lens.size)}else null;val reg=when{lens.size<2->"Veri bekleniyor";dev!!<=2->"Düzenli";dev<=5->"Değişken";else->"Düzensiz"};val cycle=ac?:28;var next=starts.lastOrNull()?.plusDays(cycle.toLong());while(next!=null&&!next.isAfter(LocalDate.now()))next=next.plusDays(cycle.toLong());val ovu=next?.minusDays(14);return Stats(ac,ap,lens,next,ovu,ovu?.minusDays(5),ovu?.plusDays(1),reg,dev)}
private fun durations(xs:List<DayEntry>):List<Int>{val s=xs.filter{it.start}.map{it.date}.distinct().sorted();val e=xs.filter{it.end}.map{it.date}.distinct().sorted();return s.mapIndexedNotNull{i,a->val n=s.getOrNull(i+1);e.firstOrNull{!it.isBefore(a)&&(n==null||it.isBefore(n))}?.let{ChronoUnit.DAYS.between(a,it).toInt()+1}?.takeIf{it in 1..15}}}
private fun intervals(xs:List<DayEntry>):List<Interval>{val s=xs.filter{it.start}.map{it.date}.distinct().sorted();val e=xs.filter{it.end}.map{it.date}.distinct().sorted();val now=LocalDate.now();return s.mapIndexed{i,a->val n=s.getOrNull(i+1);val real=e.firstOrNull{!it.isBefore(a)&&(n==null||it.isBefore(n))};val end=real?:when{a.isAfter(now)->a;ChronoUnit.DAYS.between(a,now)<=9->now;else->a.plusDays(4)};Interval(a,end)}}
private fun history(xs:List<DayEntry>):List<Pair<LocalDate,LocalDate?>>{val s=xs.filter{it.start}.map{it.date}.distinct().sorted();val e=xs.filter{it.end}.map{it.date}.distinct().sorted();return s.mapIndexed{i,a->val n=s.getOrNull(i+1);a to e.firstOrNull{!it.isBefore(a)&&(n==null||it.isBefore(n))}}.reversed()}
private fun isPred(d:LocalDate,s:Stats):Boolean{val a=s.next?:return false;val b=a.plusDays(((s.avgPeriod?:5)-1).toLong());return !d.isBefore(a)&&!d.isAfter(b)}
private fun headline(s:Stats):String{val n=s.next?:return "İlk başlangıç kaydını ekleyerek tahminleri başlat.";val d=ChronoUnit.DAYS.between(LocalDate.now(),n).toInt();return when(d){0->"Tahmine göre regl bugün başlayabilir.";1->"Tahmine göre regle 1 gün kaldı.";else->"Tahmine göre regle $d gün kaldı."}}
private fun shortDate(d:LocalDate)=d.format(DateTimeFormatter.ofPattern("d MMM yyyy",Locale("tr","TR")))
private fun longDate(d:LocalDate)=d.format(DateTimeFormatter.ofPattern("d MMMM yyyy, EEEE",Locale("tr","TR"))).replaceFirstChar{it.uppercase(Locale("tr","TR"))}
